name: human_activity_recognition
description: "Flutter package that uses the device's built-in sensors (like accelerometer and gyroscope) to detect and classify human activities, such as walking, running, sitting, standing, etc. This package can be useful in fitness apps, health monitoring apps, and even IoT applications."
version: 0.0.1
homepage: https://github.com/rishirizz/human_activity_recognition

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.0.1
  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.human_activity_recognition
        pluginClass: HumanActivityRecognitionPlugin
      ios:
        pluginClass: HumanActivityRecognitionPlugin
 